# Generated by Django 6.0.7 on 2026-09-01 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('organization', 'Organization'), ('mentor', 'Mentor')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('grade', models.CharField(blank=True, max_length=30)),
                ('school', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('can_offer', models.TextField(blank=True)),
                ('looking_for', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('availability', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
