# Generated by Django 6.0.7 on 2026-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='club_interest',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords describing the student.'),
        ),
    ]
