# Generated by Django 5.2.17 on 2026-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_club_interest_studentprofile_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12'), ('graduate', 'Graduate / alumni')], max_length=30),
        ),
    ]
