# Generated by Django 6.0.7 on 2026-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords describing this club.'),
        ),
    ]
