# Generated by Django 6.0.7 on 2026-09-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('internship', 'Internship'), ('volunteering', 'Volunteering'), ('competition', 'Competition'), ('research', 'Research'), ('summer_program', 'Summer Program'), ('scholarship', 'Scholarship'), ('hackathon', 'Hackathon'), ('leadership', 'Leadership'), ('event', 'Event')], default='internship', max_length=30)),
                ('description', models.TextField()),
                ('skills_needed', models.TextField(blank=True)),
                ('who_should_apply', models.TextField(blank=True)),
                ('time_commitment', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
