CLUB_CHOICES = [
    ("AP Human Help Club", "AP Human Help Club"),
    ("Asian Cultural Club", "Asian Cultural Club"),
    ("ASLHS (American Sign Language Honor Society)", "ASLHS (American Sign Language Honor Society)"),
    ("Beaches Go Green", "Beaches Go Green"),
    ("Best Buddies", "Best Buddies"),
    ("Better in a Letter", "Better in a Letter"),
    ("Bible Study", "Bible Study"),
    ("Biotechnology Club", "Biotechnology Club"),
    ("Birthday Boxes PV", "Birthday Boxes PV"),
    ("Book Club", "Book Club"),
    ("Breast Cancer Breakthrough", "Breast Cancer Breakthrough"),
    ("Car Enthusiasts of PV", "Car Enthusiasts of PV"),
    ("Cards and Board games", "Cards and Board games"),
    ("Care Through Cards", "Care Through Cards"),
    ("Chess Club", "Chess Club"),
    ("Civic Coalition Initiative", "Civic Coalition Initiative"),
    ("Club Politico", "Club Politico"),
    ("Creative Writing Club", "Creative Writing Club"),
    ("Cultural Collective", "Cultural Collective"),
    ("Cultural Connections", "Cultural Connections"),
    ("Curbside Cleanup", "Curbside Cleanup"),
    ("CURE & CARE", "CURE & CARE"),
    ("Debate TEAM", "Debate TEAM"),
    ("DECA", "DECA"),
    ("Documentary Club", "Documentary Club"),
    ("Dungeons and Dragons", "Dungeons and Dragons"),
    ("Dyslexia Superpower", "Dyslexia Superpower"),
    ("ESPV", "ESPV"),
    ("Faith Girls", "Faith Girls"),
    ("Family Promise", "Family Promise"),
    ("Fellowship of Christian Athletes", "Fellowship of Christian Athletes"),
    ("Fiber Arts club", "Fiber Arts club"),
    ("Firehouse Project", "Firehouse Project"),
    ("First Down For Families", "First Down For Families"),
    ("Florida Future Educators of America (FFEA)", "Florida Future Educators of America (FFEA)"),
    ("GenWOW", "GenWOW"),
    ("Girl Up", "Girl Up"),
    ("Girls Empowering Math and Science (GEMS)", "Girls Empowering Math and Science (GEMS)"),
    ("Glam for Good", "Glam for Good"),
    ("Glamour Gals", "Glamour Gals"),
    ("Golf Fights Cancer", "Golf Fights Cancer"),
    ("Habitat for Humanity Chapter", "Habitat for Humanity Chapter"),
    ("Hearts of Ponte Vedra", "Hearts of Ponte Vedra"),
    ("Her Song", "Her Song"),
    ("HerSpace", "HerSpace"),
    ("High Schools Against Cancer", "High Schools Against Cancer"),
    ("HighQ", "HighQ"),
    ("Honor Huddle", "Honor Huddle"),
    ("Hope In Action", "Hope In Action"),
    ("HOSA- Health Occupation Students of America", "HOSA- Health Occupation Students of America"),
    ("Ignite Learning", "Ignite Learning"),
    ("Interact", "Interact"),
    ("International Thespian Society", "International Thespian Society"),
    ("Investing Initiative", "Investing Initiative"),
    ("JaxTHRIVE", "JaxTHRIVE"),
    ("Jaywing", "Jaywing"),
    ("Jewish Student Union", "Jewish Student Union"),
    ("K9s4Warriors", "K9s4Warriors"),
    ("KIDS", "KIDS"),
    ("Lawyers in the Making", "Lawyers in the Making"),
    ("Lift Up Club", "Lift Up Club"),
    ("LinkedIn 101", "LinkedIn 101"),
    ("Little Love Baskets", "Little Love Baskets"),
    ("LoveMeTrue Cat Rescue Club", "LoveMeTrue Cat Rescue Club"),
    ("Media Seminar", "Media Seminar"),
    ("MedImpact", "MedImpact"),
    ("Mind Over Matter", "Mind Over Matter"),
    ("Missing Childs Project", "Missing Childs Project"),
    ("Model United Nations and World Affairs Club", "Model United Nations and World Affairs Club"),
    ("Morgan's Message", "Morgan's Message"),
    ("Movie Club", "Movie Club"),
    ("MSA (Muslim Student Association)", "MSA (Muslim Student Association)"),
    ("Mu Alpha Theta", "Mu Alpha Theta"),
    ("National Art Honor Society (NAHS)", "National Art Honor Society (NAHS)"),
    ("National English Honor Society", "National English Honor Society"),
    ("National Hispanic Honor Society", "National Hispanic Honor Society"),
    ("National Honor Society", "National Honor Society"),
    ("Percussive Arts", "Percussive Arts"),
    ("PET Safe Rescue", "PET Safe Rescue"),
    ("Petals of Purpose", "Petals of Purpose"),
    ("Pickleball Club", "Pickleball Club"),
    ("Ponte Vedra Active Awareness", "Ponte Vedra Active Awareness"),
    ("Poseforward", "Poseforward"),
    ("Power of Movement", "Power of Movement"),
    ("Psychology Club", "Psychology Club"),
    ("PV 4 Pace", "PV 4 Pace"),
    ("Rocketry Club", "Rocketry Club"),
    ("Science National Honors Society", "Science National Honors Society"),
    ("Science Olympiad Club", "Science Olympiad Club"),
    ("See The Girl", "See The Girl"),
    ("Sending Sunshine", "Sending Sunshine"),
    ("Senior Women", "Senior Women"),
    ("Sharks For Soldiers", "Sharks For Soldiers"),
    ("Student Government", "Student Government"),
    ("Students Against Destructive Decisions (S.A.D.D.)", "Students Against Destructive Decisions (S.A.D.D.)"),
    ("Suds for Success", "Suds for Success"),
    ("Technical Theatre Club", "Technical Theatre Club"),
    ("Technology Club", "Technology Club"),
    ("TED Ed Student Talks", "TED Ed Student Talks"),
    ("The C.A.R.E. collective", "The C.A.R.E. collective"),
    ("The Giving Shelf", "The Giving Shelf"),
    ("The SPKSB", "The SPKSB"),
    ("Tidebreak", "Tidebreak"),
    ("Tri-M Honor Society", "Tri-M Honor Society"),
    ("Unity for Ukraine", "Unity for Ukraine"),
    ("Wise Moves", "Wise Moves"),
    ("Women in Surgery", "Women in Surgery"),
]
